name: Chart pipeline

on:
  push:
    branches: [main]
    tags:
      - image@v*
    paths:
      - CHANGELOG.md
      - chart/**
      - values.yaml
      - .github/workflows/main.yml
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  long-running-test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Long running test"
          sleep 30

  debug:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Event type: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Ref type: ${{ github.ref_type }}"
          echo "Ref name: ${{ github.ref_name }}"


  only-commit:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - run: |
          echo "Only commit"


  only-tag:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    steps:
      - run: |
          echo "Only tag"

  only-tag-special:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag' && startsWith(github.ref_name, 'image@v')
    steps:
      - run: |
          echo "Only tag special"

  integration-test-reusable:
    uses: jneuff/test-actions/.github/workflows/reusable.yaml@main

  release-please:
    runs-on: ubuntu-latest
    if: >
      github.event_name != 'pull_request' || 
      !startsWith(github.event.pull_request.title, 'chore(main): release')
    needs: ["integration-test-reusable"]
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }}
    steps:
      - id: release-please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.PAT_PR }}
      - if: ${{ steps.release-please.outputs.release_created }}
        run: echo ${{ steps.release-please.outputs.tag_name }}
      - if: ${{ needs.integration-test-reusable.result }} == 'success'
        run: echo "integration tests pass"

  separate-job:
    runs-on: ubuntu-latest
    needs: ["integration-test-reusable", "release-please"]
    steps:
      - run: |
          echo "Separate job"
          echo "${{ toJson(needs.release-please.outputs) }}"
      - if: ${{ needs.release-please.outputs.release_created }} && ${{ needs.integration-test-reusable.result }} == 'success'
        run: echo ${{ needs.release-please.outputs.tag_name }}
